/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Info.GetSentences;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.Timer;
import org.json.JSONArray;

/**
 *
 * @author Alisser
 */
public class Principal extends javax.swing.JFrame implements ActionListener {

    GetSentences info = new GetSentences();
    JSONArray words;

    /**
     * Creates new form Principal
     */
    public Principal() throws IOException {
        this.words = info.Words();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));

        jLabel2.setFont(new java.awt.Font("Monocraft", 1, 36)); // NOI18N
        jLabel2.setText("ORDER THE WORDS");

        jLabel3.setFont(new java.awt.Font("Monocraft", 1, 24)); // NOI18N
        jLabel3.setText("Score:");

        jLabel4.setFont(new java.awt.Font("Monocraft", 1, 24)); // NOI18N
        jLabel4.setText("0");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Monocraft", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(15000, 15000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(15000, 15000));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Minecraft", 1, 18)); // NOI18N
        jLabel1.setText("Correct!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(140, 140, 140)
                                .addComponent(jButton1)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Init initWindow = new Init();
        initWindow.setVisible(true);
        initWindow.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void WordsToLabel() throws IOException {
        jLabel1.setVisible(false);
        ArrayList<String> wordsList = new ArrayList<>();
        for (int i = 0; i < words.length(); i++) {
            String word = words.getString(i);
            wordsList.add(word);
        }
        Collections.shuffle(wordsList);
        JSONArray wordsDisorder = new JSONArray(wordsList);
        int rows = (int) Math.ceil(wordsDisorder.length() / 6.0);
        jPanel1.setLayout(new GridLayout(rows, 6));
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT));
        jPanel1.setMinimumSize(new Dimension(460, 80));
        jPanel1.setPreferredSize(new Dimension(460, 80));
        jPanel1.setMaximumSize(new Dimension(460, 80));
        jPanel2.setLayout(new GridLayout(rows, 6));
        jPanel2.setLayout(new FlowLayout(FlowLayout.LEFT));
        jPanel2.setMinimumSize(new Dimension(460, 80));
        jPanel2.setPreferredSize(new Dimension(460, 80));
        jPanel2.setMaximumSize(new Dimension(460, 80));
        for (int i = 0; i < wordsDisorder.length(); i++) {
            JButton word = new JButton(wordsDisorder.getString(i));
            word.addActionListener(this);
            word.setBounds(10, 10, 200, 100);
            jPanel1.add(word);
        }
    }

    /**
     *
     * @param e
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton button) {
            String buttonText = button.getText();
            JButton wordSelected = new JButton(buttonText);
            wordSelected.addActionListener(this);
            wordSelected.setBounds(10, 10, 200, 100);
            Container parent = button.getParent();
            if (parent == jPanel1) {
                jPanel1.remove(button);
                jPanel1.repaint();
                jPanel2.add(wordSelected);
                jPanel2.revalidate();
            } else if (parent == jPanel2) {
                jPanel2.remove(button);
                jPanel2.repaint();
                jPanel1.add(wordSelected);
                jPanel1.revalidate();
            }
            if (jPanel2.getComponentCount() == words.length()) {
                JSONArray sentence = new JSONArray();
                Component[] components = jPanel2.getComponents();
                for (Component component : components) {
                    if (component instanceof JButton) {
                        JButton word = (JButton) component;
                        String text = word.getText();
                        sentence.put(text);
                    }
                }
                StringBuilder sentenceTrue = new StringBuilder();
                StringBuilder sentenceUser = new StringBuilder();
                for (int i = 0; i < words.length(); i++) {
                    sentenceTrue.append(words.getString(i) + " ");
                    sentenceUser.append(sentence.getString(i) + " ");
                }
                Timer timer = new Timer(1000, (ActionEvent e1) -> {
                        // Aquí es donde ocultaremos el JLabel
                        jLabel1.setVisible(false);
                        try {
                            this.words = info.Words();
                            this.WordsToLabel();
                        } catch (IOException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                if (sentenceTrue.toString().equals(sentenceUser.toString())) {
                    String value = jLabel4.getText();
                    String plus = Integer.toString(Integer.parseInt(value) + 1);
                    jLabel4.setText(plus);
                    jLabel1.setText("Correct!");
                    jLabel1.setVisible(true);
                    timer.setRepeats(false);
                    timer.start();
                    jPanel2.removeAll();
                    jPanel2.repaint();
                } else {
                    jLabel1.setText("Incorrect!");
                    jLabel1.setVisible(true);
                    timer.setRepeats(false);
                    timer.start();
                    jPanel2.removeAll();
                    jPanel2.repaint();
                }
            }
        }
    }

    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
